version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: queens
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  app:
    image: reinas
    volumes:
    - .:/src
    working_dir: /src
    command: python src/queens.py

volumes:
    pgdata:


  
